language: ruby
dist: bionic
addons:
  postgresql: 10.12
before_install:
  - gem install bundler
before_script:
  - cp config/database.yml.travis config/database.yml
  - bin/rails db:create
script:
  - bundle exec rails db:migrate RAILS_ENV=test
