# set defaults for development and testing under Docker
# production will need to work with Heroku
docker-default: &docker-default
  adapter: postgresql
  encoding: utf8
  host: postgres
  username: postgres
  password:
  pool: 5

development:
  <<: *docker-default
  database: sensor_bucket_development

test:
  <<: *docker-default
  database: sensor_bucket_test

production:
  encoding: utf8
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: <%= ENV['POSTGRESQL_HOSTNAME'] %>
  username: <%= ENV['POSTGRESQL_USERNAME'] %>
  password: <%= ENV['POSTGRESQL_PASSWORD'] %>
  port: <%= ENV['POSTGRESQL_PORT'] %>
  database: recorder_production
